name: Deploy ke GitHub Pages dengan Secret
on:
  push:
    # Otomatis berjalan baik nama branch Anda "main" ataupun "master"
    branches: ["main", "master"] 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode (Checkout)
        uses: actions/checkout@v4

      - name: Suntikkan API Secret LPKA ke Semua File JS
        # Perintah ini akan mencari semua file .js di folder manapun, 
        # lalu mengganti placeholder menjadi URL asli Anda.
        run: |
          find . -type f -name "*.js" -exec sed -i "s|URL_API_RAHASIA_LPKA|${{ secrets.API_LPKA }}|g" {} +

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Membaca seluruh file di repositori
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
